meta:
  root_dir: /notebooks/BKAI/DB_text_minimal
  round_number: 8
  debug: False
  device: cuda
  test_device: cpu
  use_eval: True
  join_training: True

hps:
  batch_size: 12
  test_batch_size: 1  # must be set to 1 to evaluate metric
  img_size: 640
  test_img_size: 640  # pdf
  no_epochs: 20
  warmup_epochs: 10
  no_classes: 2
  log_iter: 10

lrs:
  mode: poly  # reduce / poly
  max_iters: 0
  warmup_iters: 200
  factor: 0.5
  patience: 2

augmentation:

callbacks:

data:

  BKAI:
    train_dir: /notebooks/BKAI/dataset/training_img
    test_dir: /notebooks/BKAI/dataset/test_img
    train_gt_dir: /notebooks/BKAI/dataset/training_gt
    test_gt_dir: /notebooks/BKAI/dataset/test_gt
    ignore_tags: ["###"]

dataset:
  name: BKAI
  return_dict: True

logging:
  logger_file: train.log

loss:

model:
  backbone: resnet  # mini_resnet / resnet / regvgg
  finetune_cp_path: models/best_hmean_regvgg_join_0807.pth
  best_cp_path: models/best_cp_regvgg_join_0907.pth
  last_cp_path: models/epoch
  final_cp_path: models/final.pth
  best_hmean_cp_path: models/best_hmean.pth

optimizer:
  type: adam
  lr: 0.0075
  lr_finetune: 0.001
  weight_decay: 0.0
  reduction: mean
  alpha: 1
  beta: 10
  negative_ratio: 3
  amsgrad: False

metric:
  thred_text_score: 0.30
  prob_threshold: 0.50
  unclip_ratio: 1.60
  is_output_polygon: True

private:

scheduler:

trainer:

training: