name: testing

on: 
  push: 
    branches:
      - main  
      - master

jobs:
  test-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.1
      - name: Install dependencies
        run: pip install pytest
      - name: Execute tests
        run: pytest